name: Add Chore Task
description: Adds a new task for a chore
title: "[Chore]: "
labels:
  - "chore"
projects:
  - "MotionWindUI/1"
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the information below to add a new chore task
  - type: textarea
    id: description
    attributes:
      label: What is the chore?
      description: Please describe the chore.
      placeholder: |
        (Description)
  - type: checkboxes
    id: modification
    attributes:
      label: Does this modify an existing package?
      description: Will this chore modify/add to an existing package?
      options:
        - label: Yes
          required: false
  - type: dropdown
    id: packages
    attributes:
      label: If it modifies an existing package, which one?
      description: If this chore adds/modifies an existing package, which package?
      multiple: true
      options:
        - "@motionwindui/base"
        - "@motionwindui/theme"
        - "@motionwindui/provider"
        - "@motionwindui/heroicons-icons"
        - "@motionwindui/react-utils"
        - "@motionwindui/button"
  - type: dropdown
    id: area
    attributes:
      label: Which area?
      description: Which area of the project/monorepo does this target?
      multiple: true
      options:
        - components
        - core
        - utils