name: Add Fix Task
description: Adds a new task to fix a bug
title: "[Fix]: "
labels:
  - "fix"
projects:
  - "MotionWindUI/1"
assignees:
  - Kyle-Gagnon-99
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the information below to add a new bug fix task
  - type: textarea
    id: description
    attributes:
      label: What does it fix?
      description: What does this task aim to fix? What is the issue number?
      placeholder: |
        This task fixes...

        1. Closes #(Issue Number)
  - type: dropdown
    id: area
    attributes:
      label: Which area?
      description: Which area of the project/monorepo does this target
      multiple: true
      options:
        - components
        - core
        - utilities
  - type: dropdown
    id: component-fix
    attributes:
      label: Any component?
      description: If this fixes a component(s) which one does it fix?
      multiple: true
      options:
        - button
  - type: textarea
    id: extra-info
    attributes:
      label: Extra Information
      description: Any extra information about this bug/fix? (Any ideas?)