name: Add Refactor Task
description: Adds a new task to refactor code
labels:
  - "refactor"
projects:
  - "MotionWindUI/1"
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the information below to add a new refactor task
  - type: textarea
    id: description
    attributes:
      label: What is being refactored?
      description: Please describe what is being refactored.
      placeholder: |
        (Description)
  - type: checkboxes
    id: modification
    attributes:
      label: Does this modify an existing package?
      description: Will this refactor modify/add to an existing package?
      options:
        - label: Yes
          required: false
  - type: dropdown
    id: packages
    attributes:
      label: If it modifies an existing package, which one?
      description: If this refactor adds/modifies an existing package, which package?
      multiple: true
      options:
        - "@motionwindui/base"
        - "@motionwindui/theme"
        - "@motionwindui/provider"
        - "@motionwindui/heroicons-icons"
        - "@motionwindui/react-utils"
        - "@motionwindui/button"
  - type: checkboxes
    id: new-package
    attributes:
      label: Does this add a new package?
      description: Will this refactor be a new package?
      options:
        - label: Yes
          required: false
  - type: dropdown
    id: area
    attributes:
      label: Which area?
      description: Which area of the project/monorepo does this target?
      multiple: true
      options:
        - components
        - core
        - utils