name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels:
  - "bug"
  - "triage"
projects:
  - "MotionWindUI/1"
assignees:
  - Kyle-Gagnon-99
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you saw!
      value: "A bug has appeared!"
  - type: dropdown
    id: area
    attributes:
      label: Which package?
      description: Which of the following packages do you think the bug is in? It's ok if you aren't sure, but if you could select what you are using that will also be helpful!
      multiple: true
      options:
        - "@motionwindui/base"
        - "@motionwindui/theme"
        - "@motionwindui/button"
  - type: dropdown
    id: browsers
    attributes:
      label: What browseres are you seeing the problem on?
      description: What browsers did the bug occur on? (You don't have to select ones that you don't have)
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks
      render: shell
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that you think may help us figure out more about the bug?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/MotionWindUI/MotionWindUI/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
