name: Feature Request
description: Request a new feature.
title: "[Feature]: "
labels:
  - "feature"
projects:
  - "MotionWindUI/1"
assignees:
  - Kyle-Gagnon-99
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking interest in the project!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you to find out more if we need to?
      placeholder: example@email.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see added?
      placeholder: Tell us what you would like to see!
  - type: dropdown
    id: area
    attributes:
      label: Which area of the project?
      description: Which area of the project would this new feature go to?
      multiple: true
      options:
        - "New Component"
        - "New Utility"
        - "New Style"
        - "Existing Component"
        - "Existing Utility"
        - "Existing Style"
  - type: dropdown
    id: if-existing
    attributes:
      label: If an existing area, which one?
      description: If the feature is to be in an existing area of the project, which one?
      multiple: true
      options:
        - "@motionwindui/base"
        - "@motionwindui/theme"
        - "@motionwindui/button"
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: |
        Anything else you would like to add? Maybe images? Figma link? Prototype?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/MotionWindUI/MotionWindUI/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
