on:
  push:
    branches:
      - main

jobs:
  deploy_sb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/workflows/common-actions/install

      - name: Build Storybook
        run: pnpm build:sb

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/storybook/storybook-static
          destination_dir: storybook
          publish_branch: main
